spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    azure:
      active-directory:
        enabled: true
        credential.client-id: 58efa4d5-62e8-4b3c-82ac-b0720c84f829
        profile.tenant-id: common
        post-logout-redirect-uri: http://localhost:8080
        authorization-clients:
          graph:
            scopes:
              - https://graph.microsoft.com/User.Read
      storage:
        blob:
          endpoint: https://memoblob.blob.core.windows.net/
        account-name: memoblob


database.endpoint: https://memo-storage.documents.azure.com:443/
keyvault.endpoint: https://memo-keyvault.vault.azure.net/