package com.example.memo;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for the {@link Memo} POJO.
 *
 * <p>Because {@code Memo} only contains plain fields with standard getters/setters,
 * the tests focus on the round‑trip behavior of each property.
 *
 * <p><strong>NOTE:</strong> This test class was generated by an AI assistant.</p>
 *
 * @author AI
 */
class MemoUnitTest {

    /* --------------------------------------------------------------------- */
    /* 1.  Getter / Setter round‑trip for every field                       */
    /* --------------------------------------------------------------------- */

    @Test
    @DisplayName("id getter/setter round‑trip")
    void idRoundTrip() {
        Memo m = new Memo();
        m.setId("123");
        assertThat(m.getId()).isEqualTo("123");
    }

    @Test
    @DisplayName("userId getter/setter round‑trip")
    void userIdRoundTrip() {
        Memo m = new Memo();
        m.setUserId("user-xyz");
        assertThat(m.getUserId()).isEqualTo("user-xyz");
    }

    @Test
    @DisplayName("title getter/setter round‑trip")
    void titleRoundTrip() {
        Memo m = new Memo();
        m.setTitle("My Title");
        assertThat(m.getTitle()).isEqualTo("My Title");
    }

    @Test
    @DisplayName("content getter/setter round‑trip")
    void contentRoundTrip() {
        Memo m = new Memo();
        m.setContent("Some content");
        assertThat(m.getContent()).isEqualTo("Some content");
    }

    @Test
    @DisplayName("x getter/setter round‑trip")
    void xRoundTrip() {
        Memo m = new Memo();
        m.setX(42);
        assertThat(m.getX()).isEqualTo(42);
    }

    @Test
    @DisplayName("y getter/setter round‑trip")
    void yRoundTrip() {
        Memo m = new Memo();
        m.setY(-7);
        assertThat(m.getY()).isEqualTo(-7);
    }

    @Test
    @DisplayName("type getter/setter round‑trip")
    void typeRoundTrip() {
        Memo m = new Memo();
        m.setType(Type.STICKY_NOTE);
        assertThat(m.getType()).isEqualTo(Type.STICKY_NOTE);
    }

    /* --------------------------------------------------------------------- */
    /* 2.  Null handling – the class should accept nulls without throwing   */
    /* --------------------------------------------------------------------- */

    @Test
    @DisplayName("null values are preserved")
    void nullValues() {
        Memo m = new Memo();
        m.setId(null);
        m.setUserId(null);
        m.setTitle(null);
        m.setContent(null);
        m.setType(null);

        assertThat(m.getId()).isNull();
        assertThat(m.getUserId()).isNull();
        assertThat(m.getTitle()).isNull();
        assertThat(m.getContent()).isNull();
        assertThat(m.getType()).isNull();
    }
}
