package com.example.memo;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.*;

/**
 * Unit tests for the {@link Type} enum.
 *
 * <p><strong>NOTE:</strong> This test class was generated by an AI assistant.</p>
 *
 * @author AI
 */
class TypeUnitTest {

    /* --------------------------------------------------------------------- */
    /* 1.  toString() – the JSON value exposed by the enum                   */
    /* --------------------------------------------------------------------- */

    @Test
    @DisplayName("toString() returns the display name")
    void toStringReturnsDisplayName() {
        assertThat(Type.STICKY_NOTE.toString()).isEqualTo("StickyNote");
        assertThat(Type.BIG_SHEET.toString()).isEqualTo("BigSheet");
    }

    /* --------------------------------------------------------------------- */
    /* 2.  fromString() – case‑insensitive lookup and error handling         */
    /* --------------------------------------------------------------------- */

    @Nested
    @DisplayName("fromString() – valid values")
    class ValidValues {

        @Test
        @DisplayName("exact match")
        void exactMatch() {
            assertThat(Type.fromString("StickyNote")).isEqualTo(Type.STICKY_NOTE);
            assertThat(Type.fromString("BigSheet")).isEqualTo(Type.BIG_SHEET);
        }

        @Test
        @DisplayName("case‑insensitive")
        void caseInsensitive() {
            assertThat(Type.fromString("stickynote")).isEqualTo(Type.STICKY_NOTE);
            assertThat(Type.fromString("BIGSHEET")).isEqualTo(Type.BIG_SHEET);
        }

        @Test
        @DisplayName("whitespace trimmed")
        void whitespaceTrimmed() {
            assertThat(Type.fromString("  StickyNote  ")).isEqualTo(Type.STICKY_NOTE);
            assertThat(Type.fromString("\tBigSheet\n")).isEqualTo(Type.BIG_SHEET);
        }
    }

    @Nested
    @DisplayName("fromString() – error cases")
    class ErrorCases {

        @Test
        @DisplayName("unknown value throws IllegalArgumentException")
        void unknownValue() {
            assertThatThrownBy(() -> Type.fromString("Unknown"))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessageContaining("Unknown type: Unknown");
        }

        @Test
        @DisplayName("null returns null")
        void nullInput() {
            assertThat(Type.fromString(null)).isNull();
        }
    }

    /* --------------------------------------------------------------------- */
    /* 3.  Map integrity – the internal lookup map contains all enum values   */
    /* --------------------------------------------------------------------- */

    @Test
    @DisplayName("internal map contains all display names in lower case")
    void mapIntegrity() {
        // We cannot access _MAP_ directly, but we can infer its contents
        // by ensuring that every enum value can be resolved via fromString
        // using its display name in lower case.
        for (Type t : Type.values()) {
            String lower = t.toString().toLowerCase();
            assertThat(Type.fromString(lower)).isEqualTo(t);
        }
    }
}
