name: Enforce Version

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches:
      - main

jobs:
  enforce-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: |
            patch
            minor
            major
          add_comment: true
          message: "This pull request is being blocked from merging, because a version label is missing. Please assign either patch, minor or major label."
